-- MySQL Script generated by MySQL Workbench
-- lun. 27 juin 2022 00:13:14
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AreUHere
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AreUHere` ;

-- -----------------------------------------------------
-- Schema AreUHere
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AreUHere` ;
USE `AreUHere` ;

-- -----------------------------------------------------
-- Table `AreUHere`.`USER`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER` (
  `email` VARCHAR(255) NOT NULL,
  `username` VARCHAR(16) NOT NULL,
  `activityMessage` VARCHAR(120) NULL,
  `password` BINARY(255) NOT NULL,
  `isVerified` TINYINT NOT NULL DEFAULT 0,
  `role` ENUM("admin", "intervenant", "participant") NOT NULL DEFAULT 'participant',
  `isConnected` TINYINT NOT NULL DEFAULT 0,
  `isBlackListed` TINYINT NOT NULL DEFAULT 0,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `AreUHere`.`USER_LOGO`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER_LOGO` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER_LOGO` (
  `path` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `seed` INT NOT NULL,
  `sizeMo` INT NOT NULL,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_LOGO_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_LOGO_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `AreUHere`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AreUHere`.`USER_IP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER_IP` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER_IP` (
  `ip` VARCHAR(16) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_IP_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_IP_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `AreUHere`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AreUHere`.`USER_MACADDRESS`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER_MACADDRESS` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER_MACADDRESS` (
  `macAddress` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_MACADDRESS_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_MACADDRESS_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `AreUHere`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AreUHere`.`USER_DEVICE`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER_DEVICE` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER_DEVICE` (
  `device` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `active` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  INDEX `fk_USER_DEVICE_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_DEVICE_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `AreUHere`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AreUHere`.`USER_HISTORY`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER_HISTORY` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER_HISTORY` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `isMessage` TINYINT NOT NULL DEFAULT 0,
  `isAction` TINYINT NOT NULL DEFAULT 0,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_HISTORY_1_idx` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_HISTORY_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `AreUHere`.`USER` (`uuid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AreUHere`.`USER_ACTION`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER_ACTION` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER_ACTION` (
  `log` VARCHAR(255) NOT NULL,
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `userHistoryUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_ACTION_1_idx` (`userHistoryUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_ACTION_1`
    FOREIGN KEY (`userHistoryUuid`)
    REFERENCES `AreUHere`.`USER_HISTORY` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AreUHere`.`USER_REPORT`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER_REPORT` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER_REPORT` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `reason` TEXT NOT NULL,
  `userSendReport` BINARY(16) NOT NULL,
  `userReported` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_REPORT_1_idx` (`userSendReport` ASC) VISIBLE,
  INDEX `fk_USER_REPORT_2_idx` (`userReported` ASC) VISIBLE,
  CONSTRAINT `fk_USER_REPORT_1`
    FOREIGN KEY (`userSendReport`)
    REFERENCES `AreUHere`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USER_REPORT_2`
    FOREIGN KEY (`userReported`)
    REFERENCES `AreUHere`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AreUHere`.`USER_TOKEN`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AreUHere`.`USER_TOKEN` ;

CREATE TABLE IF NOT EXISTS `AreUHere`.`USER_TOKEN` (
  `createdAt` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `expireAt` DATETIME NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `userUuid` BINARY(16) NOT NULL,
  `uuid` BINARY(16) NOT NULL DEFAULT (UUID_TO_BIN(UUID(), TRUE)),
  UNIQUE INDEX `token_UNIQUE` (`token` ASC) VISIBLE,
  PRIMARY KEY (`uuid`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC) VISIBLE,
  INDEX `fk_USER_TOKEN_1_idx` (`userUuid` ASC) VISIBLE,
  UNIQUE INDEX `userUuid_UNIQUE` (`userUuid` ASC) VISIBLE,
  CONSTRAINT `fk_USER_TOKEN_1`
    FOREIGN KEY (`userUuid`)
    REFERENCES `AreUHere`.`USER` (`uuid`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
